name: Bug Report
description: Report a bug with the Levante API Services or an MCP listing
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below.

  - type: dropdown
    id: type
    attributes:
      label: Bug Type
      options:
        - API Issue
        - MCP Configuration Error
        - Documentation Issue
        - Other
    validations:
      required: true

  - type: input
    id: mcp
    attributes:
      label: Affected MCP (if applicable)
      description: Which MCP is affected?
      placeholder: e.g., supabase, playwright

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Call endpoint...
        3. See error...

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
